package com.raman.RollMovie.utils

import com.raman.RollMovie.model.data.detail.movie.DetailResponse
import com.raman.RollMovie.model.data.detail.movie.Genre
import com.raman.RollMovie.model.data.detail.movie.ProductionCompany
import com.raman.RollMovie.model.data.detail.movie.ProductionCountry
import com.raman.RollMovie.model.data.detail.movie.SpokenLanguage

val fakeData = DetailResponse(
    adult =false, backdrop_path ="/ySgY4jBvZ6qchrxKnBg4M8tZp8V.jpg", belongs_to_collection =null, budget =28000000, genres = arrayOf(Genre(id=27, name="Horror"), Genre(id=53, name="Thriller")), homepage ="https://www.abigailmovie.com", id =1111873, imdb_id ="tt27489557", original_language ="en", original_title ="Abigail", overview ="A group of criminals kidnaps a teenage ballet dancer, the daughter of a notorious gang leader, in order to obtain a ransom of $50 million, but over time, they discover that she is not just an ordinary girl. After the kidnappers begin to diminish, one by one, they discover, to their increasing horror, that they are locked inside with an unusual girl.", popularity =1102.818, poster_path ="/7qxG0zyt29BI0IzFDfsps62kbQi.jpg", production_companies = arrayOf(ProductionCompany(id=130448, logo_path="/yHWTTGKbOGZKUd1cp6l3uLyDeiv.png", name="Project X Entertainment", origin_country="US"), ProductionCompany(id=126588, logo_path="/cNhOITS96oOV7SCgUHxvZlWRecx.png", name="Radio Silence", origin_country="US"), ProductionCompany(id=33, logo_path="/8lvHyhjr8oUKOOy2dKXoALWKdp0.png", name="Universal Pictures", origin_country="US"), ProductionCompany(id=19367, logo_path="null", name="Vinson Films", origin_country="US")), production_countries = arrayOf(ProductionCountry(iso_3166_1="US", name="United States of America")), release_date ="2024-04-18", revenue =37546000, runtime =109, spoken_languages = arrayOf(SpokenLanguage(english_name="English", iso_639_1="en", name="English")), status ="Released", tagline ="Children can be such monsters.", title ="Abigail", video =false, vote_average =7.0, vote_count =352)
